### ISSUE TITLE
Don't plain fail on external references

### ISSUE THREAD

**Issue by thufschmitt** [nickel-lang/json-schema-to-nickel#48]
The tool [will currently barf](https://github.com/nickel-lang/json-schema-to-nickel/blob/01a96a6a8132d9f8fdfd2cacf05a9d6a1b201994/src/definitions.rs#L62) if it encounters any external reference.

Handling them might be a pain, but it could be nicer to just ignore the reference (returning a `Dyn` instead?) and keep going.

## Reproduction:

```console
$ json-schema-to-nickel <<EOF
{ "\$ref": "https://raw.githubusercontent.com/microsoft/vscode/main/extensions/configuration-editing/schemas/devContainer.codespaces.schema.json" }
EOF
thread 'main' panicked at 'not implemented', src/definitions.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vkleen** [comment]
Not handling them was in part a conscious decision to not make arbitrary network requests for converting a schema. I was hoping that actual external references would be uncommon in the wild. I suppose, turning them into `Dyn` and warning about it might be a good middle ground.

**Comment by hallettj** [comment]
I ran into the same issue. I don't mind inlining external references in a pre-processing steps - that provides an opportunity to separate network access from the schema conversion step. I looked around and found [JSON Schema $Ref Parser](https://github.com/APIDevTools/json-schema-ref-parser) which handles that pre-processing. Here is a minimal script:

```js
// index.mjs
import $RefParser from "@apidevtools/json-schema-ref-parser"

// Pass a file path, URL, or string as the last CLI argument
const input_schema = process.argv[process.argv.length - 1]
const schema = await $RefParser.bundle(input_schema, { /* options here */ })
console.log(JSON.stringify(schema, null, 2))
```

Install the $Ref Parser library with:

```sh
$ npm install @apidevtools/json-schema-ref-parser
```

And run it like this,

```sh
$ node index.mjs ./schema-with-external-references.jsonschema > inlined.jsonschema
```

In case anyone needs to tweak the parser options, they are [documented here](https://apitools.dev/json-schema-ref-parser/docs/options.html).

**Comment by yannham** [comment]
For any future reader, I've implemented the missing handling recently in js2n and wrote a small wrapper around the JSON schema ref parser lib. For a full Nix-based pipeline, see https://github.com/tweag/nickel-kubernetes/, and in particular the `flake.nix` - which mostly just pipes together the `json-schema-bundler` NPM wrapper defined in the same directory and json-schema-to-nickel. For example we could generate contracts for the whole set of Kubernetes resources
